- name: cisco_sh_ver
  hosts: all
  gather_facts: true 
  tasks:
   - name: run show version on remote devices
     cisco.ios.ios_command:
       commands:
         - show version
     register: output    #register the output in a variable named output
   - debug: var=output.stdout_lines   #print the variable at the console line by line
   
   - name: show run on remote devices
     #become: true
     cisco.ios.ios_command:
       commands: 
         - show run
     register: output    #register the output in a variable named output
   - debug: var=output.stdout_lines   #print the variable at the console line by line
